# Generated by Django 3.1.2 on 2020-11-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201101_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignedDoctor',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.patient')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.doctor')),
            ],
            options={
                'db_table': 'assigned_doctor',
            },
        ),
    ]
