# Generated by Django 3.1.2 on 2020-11-02 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_assigneddoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneddoctor',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_doctor', to='main.doctor'),
        ),
    ]
