# Generated by Django 3.1.2 on 2020-11-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201102_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
