# Generated by Django 3.1.3 on 2020-11-11 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201111_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assistantuser', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
