# Generated by Django 3.1.2 on 2020-11-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201112_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'medicine_company',
            },
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.medicinecompany'),
        ),
    ]
