# Generated by Django 3.1.2 on 2020-11-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201112_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='company_name',
        ),
        migrations.AddField(
            model_name='medicine',
            name='company_name',
            field=models.ManyToManyField(related_name='company', to='main.MedicineCompany'),
        ),
    ]
