# Generated by Django 3.1.2 on 2020-11-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201112_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmedicine',
            name='medicine',
        ),
        migrations.AddField(
            model_name='assignmedicine',
            name='medicine',
            field=models.ManyToManyField(related_name='assign_medicine', to='main.Medicine'),
        ),
    ]
