# Generated by Django 3.1.2 on 2020-11-12 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201112_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmedicine',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_medicine', serialize=False, to='main.patient'),
        ),
    ]
