# Generated by Django 3.1.2 on 2020-11-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201112_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneddoctor',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_doctor', to='main.doctor'),
        ),
        migrations.RemoveField(
            model_name='assignnurse',
            name='nurse',
        ),
        migrations.AddField(
            model_name='assignnurse',
            name='nurse',
            field=models.ManyToManyField(related_name='assign_nurse', to='main.Nurse'),
        ),
    ]
