# Generated by Django 3.1.2 on 2020-11-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201112_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(blank=True, default='_', max_length=120, null=True),
        ),
    ]
