# Generated by Django 3.1.2 on 2020-11-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201126_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='patient',
        ),
    ]
