# Generated by Django 3.1.4 on 2020-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_reportproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmedicine',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
