# Generated by Django 3.1.4 on 2020-12-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_assignmedicine_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
