# Generated by Django 3.1.4 on 2020-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_patient_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user_name',
        ),
        migrations.AddField(
            model_name='bill',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
