# Generated by Django 3.1.4 on 2020-12-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20201212_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealth',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.patient')),
                ('health_report', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'patient_health',
            },
        ),
    ]
