# Generated by Django 3.1.4 on 2020-12-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_patienthealth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assignMedicine',
        ),
    ]
