# Generated by Django 3.1.4 on 2020-12-15 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_delete_assignmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignMedicineNew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.BooleanField(default=False)),
                ('medicine', models.ManyToManyField(related_name='assign_medicine', to='main.Medicine')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_medicine', to='main.patient')),
            ],
            options={
                'db_table': 'assigned_medicine',
            },
        ),
    ]
