# Generated by Django 3.1.4 on 2020-12-15 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_assignmedicinenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmedicinenew',
            name='medicine_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
