# Generated by Django 3.1.2 on 2020-12-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_assignmedicinenew_medicine_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='solve',
            field=models.BooleanField(default=False),
        ),
    ]
