# Generated by Django 3.1.2 on 2020-12-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_feedback_solve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproblem',
            name='solve',
            field=models.BooleanField(default=False),
        ),
    ]
