# Generated by Django 3.1.2 on 2020-12-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_reportproblem_solve'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthAdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('health_report', models.CharField(blank=True, max_length=500, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'db_table': 'patient_health_add',
            },
        ),
        migrations.DeleteModel(
            name='PatientHealth',
        ),
    ]
