# Generated by Django 3.1.4 on 2020-12-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem', models.CharField(blank=True, max_length=300, null=True)),
                ('solve', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'db_table': 'problem_reports',
            },
        ),
    ]
